// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    {
      type: 'category',
      label: '📁 By File',
      items: ['code-breakdown/by-file/db-connect', 
        'code-breakdown/by-file/import-data-from-db', 
        'code-breakdown/by-file/consumer', 
        'code-breakdown/by-file/preprocess-data',
        'code-breakdown/by-file/transform-data',
        'code-breakdown/by-file/functions-main'
      ],
    },
    {
      type: 'category',
      label: '▶️ By Method',
      items: ['code-breakdown/by-method/data-cleaning', 
      ],
    },
  ],

  userStorySidebar: [
    {
      type: 'category',
      label: 'Regla 2.0 : Chatbot',
      items: ['user-stories/regla-chatbot/regla-chatbot-overview', 
        'user-stories/regla-chatbot/answering-question',
        'user-stories/regla-chatbot/workflow-automation',
      ],
    },
    {
      type: 'category',
      label: 'Workflow',
      items: ['user-stories/workflow/workflow-overview',
        'user-stories/workflow/workflow-elements',
        'user-stories/workflow/workflow-action',
        'user-stories/workflow/workflow-template',
        'user-stories/workflow/workflow-schedule',
        'user-stories/workflow/activity-history',
        'user-stories/workflow/resource-variable',
        'user-stories/workflow/workflow-api',
      ],
    },
    {
      type: 'category',
      label: 'Risk Modeling',
      items: ['user-stories/risk-modeling/rm-overview',
        'user-stories/risk-modeling/rm-steps',
        'user-stories/risk-modeling/mev-config',
        'user-stories/risk-modeling/generate-model',
        'user-stories/risk-modeling/forward-looking',
        'user-stories/risk-modeling/model-manager',
        'user-stories/risk-modeling/rm-element',
      ],
    },
  ],
   
};

export default sidebars;
